// Generated from root version.json by scripts/sync-release-version.mjs.
// Do not edit this file directly.
export const releaseMetadata = {
  productVersion: '0.1.0',
  releaseVersion: '0.1.0-alpha.1',
  channel: 'alpha',
  buildNumber: 2,
} as const;
